export const ADMIN_GET_ALL_USERS_REQUEST = 'ADMIN_GET_ALL_USERS_REQUEST';
export const ADMIN_GET_ALL_USERS_SUCCESS = 'ADMIN_GET_ALL_USERS_SUCCESS';
export const ADMIN_GET_ALL_USERS_FAILURE = 'ADMIN_GET_ALL_USERS_FAILURE';

export const ADMIN_IS_ADMIN_REQUEST = 'ADMIN_IS_ADMIN_REQUEST';
export const ADMIN_IS_ADMIN_SUCCESS = 'ADMIN_IS_ADMIN_SUCCESS';
export const ADMIN_IS_ADMIN_FAILURE = 'ADMIN_IS_ADMIN_FAILURE';
