export const ADMIN_GET_GENERAL_INFO_REQUEST = 'ADMIN_GET_GENERAL_INFO_REQUEST';
export const ADMIN_GET_GENERAL_INFO_SUCCESS = 'ADMIN_GET_GENERAL_INFO_SUCCESS';
export const ADMIN_GET_GENERAL_INFO_FAILURE = 'ADMIN_GET_GENERAL_INFO_FAILURE';
