export const GET_PUBLIC_NOTICE_REQUEST = 'GET_PUBLIC_NOTICE_REQUEST';
export const GET_PUBLIC_NOTICE_SUCCESS = 'GET_PUBLIC_NOTICE_SUCCESS';
export const GET_PUBLIC_NOTICE_FAILURE = 'GET_PUBLIC_NOTICE_FAILURE';
