export const ADMIN_GET_ALL_USERS_REQUEST = 'ADMIN_GET_ALL_USERS_REQUEST';
export const ADMIN_GET_ALL_USERS_SUCCESS = 'ADMIN_GET_ALL_USERS_SUCCESS';
export const ADMIN_GET_ALL_USERS_FAILURE = 'ADMIN_GET_ALL_USERS_FAILURE';
