export const ADMIN_CREATE_PLAYER_REQUEST = 'ADMIN_CREATE_PLAYER_REQUEST';
export const ADMIN_CREATE_PLAYER_SUCCESS = 'ADMIN_CREATE_PLAYER_SUCCESS';
export const ADMIN_CREATE_PLAYER_FAILURE = 'ADMIN_CREATE_PLAYER_FAILURE';
