export const ADMIN_CREATE_PLAYER_REQUEST = 'ADMIN_CREATE_PLAYER_REQUEST';
export const ADMIN_CREATE_PLAYER_SUCCESS = 'ADMIN_CREATE_PLAYER_SUCCESS';
export const ADMIN_CREATE_PLAYER_FAILURE = 'ADMIN_CREATE_PLAYER_FAILURE';

export const ADMIN_GET_PLAYERS_REQUEST = 'ADMIN_GET_PLAYERS_REQUEST';
export const ADMIN_GET_PLAYERS_SUCCESS = 'ADMIN_GET_PLAYERS_SUCCESS';
export const ADMIN_GET_PLAYERS_FAILURE = 'ADMIN_GET_PLAYERS_FAILURE';
