export const PROFILE_GET_PROFILE_REQUEST = 'PROFILE_GET_PROFILE_REQUEST';
export const PROFILE_GET_PROFILE_SUCCESS = 'PROFILE_GET_PROFILE_SUCCESS';
export const PROFILE_GET_PROFILE_FAILURE = 'PROFILE_GET_PROFILE_FAILURE';

export const PROFILE_CREATE_PROFILE_REQUEST = 'PROFILE_CREATE_PROFILE_REQUEST';
export const PROFILE_CREATE_PROFILE_SUCCESS = 'PROFILE_CREATE_PROFILE_SUCCESS';
export const PROFILE_CREATE_PROFILE_FAILURE = 'PROFILE_CREATE_PROFILE_FAILURE';

export const PROFILE_EDIT_PROFILE_REQUEST = 'PROFILE_EDIT_PROFILE_REQUEST';
export const PROFILE_EDIT_PROFILE_SUCCESS = 'PROFILE_EDIT_PROFILE_SUCCESS';
export const PROFILE_EDIT_PROFILE_FAILURE = 'PROFILE_EDIT_PROFILE_FAILURE';
